apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  labels:
    app: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      name: rabbitmq
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: bitnami/rabbitmq
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5672
              protocol: TCP
            - containerPort: 15672
              protocol: TCP
          env:
            - name: RABBITMQ_USERNAME
              value: "root"
            - name: RABBITMQ_PASSWORD
              value: "123456"
            - name: RABBITMQ_MANAGEMENT_ALLOW_WEB_ACCESS
              value: "true"
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec:
  selector:
    app: rabbitmq
  ports:
    - name: amqp-port
      protocol: TCP
      port: 5672
      targetPort: 5672
    - name: management-port
      protocol: TCP
      port: 15672
      targetPort: 15672
  type: ClusterIP
      