// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"user-service/internal/handler"
	"user-service/internal/repository"
	"user-service/internal/service"
)

// Injectors from wire.go:

func InitializeUserServiceHandler() (*handler.Handler, error) {
	db := repository.NewDB()
	repositoryRepository := repository.NewRepository(db)
	serviceService := service.NewService(repositoryRepository)
	handlerHandler := handler.NewHandler(serviceService)
	return handlerHandler, nil
}
